# ========================================
# BuzzTech - Configuration Netlify
# ========================================

# ===== BUILD SETTINGS =====
[build]
  # Commande de build
  command = "npm run build"
  
  # Dossier à déployer
  publish = "dist"
  
  # Variables d'environnement du build
  [build.environment]
    NODE_VERSION = "20"

# ===== HEADERS DE SÉCURITÉ =====
# Ces headers protègent ton site contre les attaques
[[headers]]
  # S'applique à toutes les pages
  for = "/*"
  
  [headers.values]
    # ===== Protection XSS =====
    X-XSS-Protection = "1; mode=block"
    
    # ===== Protection Clickjacking =====
    X-Frame-Options = "DENY"
    
    # ===== Protection MIME Sniffing =====
    X-Content-Type-Options = "nosniff"
    
    # ===== Referrer Policy =====
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # ===== Cross-Origin Policies =====
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    
    # ===== Permissions Policy =====
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=(), interest-cohort=()"
    
    # ===== Content Security Policy (CSP) =====
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com https://js.sentry-cdn.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://www.google-analytics.com https://ssl.google-analytics.com https://analytics.google.com https://www.googletagmanager.com https://*.sentry.io https://*.ingest.sentry.io https://formspree.io;
      frame-src https://www.googletagmanager.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://wa.me;
      upgrade-insecure-requests;
      block-all-mixed-content;
    """
    
    # ===== Strict Transport Security (HSTS) =====
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # ===== Cache Control =====
    Cache-Control = "public, max-age=3600, must-revalidate"
    
    # ===== Network Error Logging =====
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    
    # ===== Reporting API =====
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://buzztech.report-uri.com/a/d/g"}],"include_subdomains":true}'

# ===== HEADERS POUR FONTS =====
[[headers]]
  for = "/fonts/*"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

# ===== CACHE AGRESSIF POUR LES ASSETS =====
[[headers]]
  for = "/assets/*"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ===== HEADERS POUR IMAGES =====
[[headers]]
  for = "/images/*"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ===== HEADERS POUR SITEMAP =====
[[headers]]
  for = "/sitemap.xml"
  
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600, must-revalidate"

# ===== REDIRECTS =====
# Redirige toutes les 404 vers la page d'accueil (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ===== OPTIMISATIONS =====
# ✅ Compression Brotli activée par défaut sur Netlify
# ✅ HTTPS activé par défaut
# ✅ CDN mondial activé par défaut
# ✅ HTTP/2 & HTTP/3 activés par défaut

# ===== ENVIRONNEMENT VARIABLES =====
# Les variables d'environnement se configurent dans l'interface Netlify :
# Site settings > Environment variables
# 
# Variables requises :
# - VITE_SITE_URL=https://www.buzztech-informatique.fr
# - VITE_SITE_NAME=BuzzTech
# - VITE_WHATSAPP_NUMBER=33660352267
# 
# Variables optionnelles :
# - VITE_SENTRY_DSN=https://xxxxx@xxxxx.ingest.sentry.io/xxxxx
# - VITE_GTM_ID=GTM-XXXXXXX