# ========================================
# BuzzTech - Configuration Netlify
# ========================================

# ===== BUILD SETTINGS =====
[build]
  # Commande de build
  command = "npm run build"
  
  # Dossier à déployer
  publish = "dist"
  
  # Variables d'environnement du build
  [build.environment]
    NODE_VERSION = "20"

# ===== HEADERS DE SÉCURITÉ =====
# Ces headers protègent ton site contre les attaques
[[headers]]
  # S'applique à toutes les pages
  for = "/*"
  
  [headers.values]
    # ===== Protection XSS =====
    # Empêche le navigateur d'exécuter du code malveillant
    X-XSS-Protection = "1; mode=block"
    
    # ===== Protection Clickjacking =====
    # Empêche ton site d'être affiché dans une iframe
    X-Frame-Options = "DENY"
    
    # ===== Protection MIME Sniffing =====
    # Force le navigateur à respecter les types MIME
    X-Content-Type-Options = "nosniff"
    
    # ===== Referrer Policy =====
    # Contrôle les infos envoyées lors de la navigation
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # ===== Permissions Policy =====
    # Désactive les APIs non utilisées
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # ===== Content Security Policy (CSP) =====
    # La plus importante : définit ce qui peut s'exécuter sur ton site
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://js.sentry-cdn.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://*.sentry.io https://*.ingest.sentry.io https://formspree.io;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://wa.me;
      upgrade-insecure-requests;
    """
    
    # ===== Strict Transport Security (HSTS) =====
    # Force HTTPS pendant 1 an
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # ===== Cache Control =====
    # Cache les ressources pour 1 heure
    Cache-Control = "public, max-age=3600, must-revalidate"

# ===== CACHE AGRESSIF POUR LES ASSETS =====
# Les fichiers avec hash dans le nom peuvent être cachés longtemps
[[headers]]
  for = "/assets/*"
  
  [headers.values]
    # Cache 1 an (les fichiers ont un hash, donc safe)
    Cache-Control = "public, max-age=31536000, immutable"

# ===== REDIRECTS =====
# Redirige toutes les 404 vers la page d'accueil (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ===== ERREURS PERSONNALISÉES =====
# Page 404 personnalisée (optionnel, si tu en crées une)
# [[redirects]]
#   from = "/*"
#   to = "/404.html"
#   status = 404

# ===== OPTIMISATIONS =====
# Compression Brotli activée par défaut sur Netlify ✅
# HTTPS activé par défaut ✅
# CDN mondial activé par défaut ✅

# ===== ENVIRONNEMENT VARIABLES =====
# Les variables d'environnement se configurent dans l'interface Netlify :
# Site settings > Environment variables
# Il faudra ajouter :
# - VITE_SENTRY_DSN
# - VITE_GTM_ID
# - VITE_SITE_URL
# - etc.